DROP DATABASE IF EXISTS library_db;

CREATE DATABASE library_db;

USE library_db;

CREATE TABLE `books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `genre` VARCHAR(45) NOT NULL,
  `author` VARCHAR(100) NOT NULL,
  `pages` INT NOT NULL,
  `isbn` VARCHAR(45) NOT NULL,
  `year` INT NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));